# Generated by Django 3.2 on 2021-05-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='no_telp',
            field=models.IntegerField(verbose_name='No Telepon'),
        ),
    ]
