# Generated by Django 3.2 on 2021-06-14 09:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofileinfo_no_telp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='no_telp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='No Telepon'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/profile.jpg', upload_to='profile_pics/', verbose_name='Foto Profil'),
        ),
    ]
