# Generated by Django 3.2 on 2021-06-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210614_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='no_telp',
            field=models.IntegerField(verbose_name='No Telepon'),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/', verbose_name='Foto Profil'),
        ),
    ]
