# Generated by Django 3.2 on 2021-05-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_sampah', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(max_length=140)),
                ('gambar', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
