# Generated by Django 3.2 on 2021-06-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestasiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_sampah', models.CharField(choices=[('Plastik', 'plastik'), ('Organik', 'organik'), ('Lainnya', 'lainnya')], max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(max_length=140)),
                ('gambar', models.ImageField(blank=True, upload_to='investasi_pics/')),
            ],
        ),
    ]
